# Dockerfile used to build Centos7 Dev environment

# Usage : time docker build -t devenv:latest -f Dockerfile.dev_env .

FROM devtools

RUN echo "Setting up dev environment"

RUN yum --setopt=group_package_types=mandatory,default,optional groupinstall -y "Development Tools" 
