# This Dockerfile is used to create a cache of Development Tools for Centos 7

# Usage :

# docker build -t devtools:latest -f Dockerfile.createcache .

FROM centos:7

#enable cache
RUN sed -i 's/keepcache=0/keepcache=1/g' /etc/yum.conf

#Download Development Tools
RUN yum --setopt=group_package_types=mandatory,default,optional groupinstall -y "Development Tools"
