# Dockerfile used to build Centos7 Dev environment

# Usage : time docker build -t devenv:latest -f Dockerfile.dev_env .

# Uncomment next line and COPY line to use "Development Tools" cache
#FROM devtools:centos7 as dev_tool_cache

FROM centos:7 

#COPY --from=dev_tool_cache /var/cache/yum/x86_64 /var/cache/yum/x86_64

RUN echo "Setting up dev environment"

RUN yum --setopt=group_package_types=mandatory,default,optional groupinstall -y "Development Tools" 
